# .github/workflows/push-dist.yml
name: Push dist
on:
  push:
    branches:
      - main
      - master

jobs:
  push-dist:
    name: "Push dist"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - uses: kategengler/put-built-npm-package-contents-on-branch@v1.0.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}-dist
          working-directory: ember-click-outside-modifier
          token: ${{ secrets.GITHUB_TOKEN }}
